name: sim-caravel-icarus
on: [push]

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Caravel-lite
        uses: actions/checkout@v2
        with:
          path: caravel-lite
      - name: Checkout pdk
        uses: actions/checkout@v2
        with:
          repository: olofk/pdklite
          path: pdklite
      - run: wget https://github.com/stnolting/riscv-gcc-prebuilt/releases/download/rv32i-2.0.0/riscv32-unknown-elf.gcc-10.2.0.rv32i.ilp32.newlib.tar.gz -O - | tar xz
      - run: echo $GITHUB_WORKSPACE/bin >> $GITHUB_PATH
      - run: sudo apt install iverilog
      - run: pip3 install fusesoc
      - run: fusesoc library add caravel $GITHUB_WORKSPACE/caravel-lite
      - run: fusesoc library add pdk $GITHUB_WORKSPACE/pdklite
      - name: Cache Primes
        id: cache-primes
        uses: actions/cache@v2
        with:
          path: $GITHUB_WORKSPACE
          key: ${{ runner.os }}-primes

  sim-icarus:
    needs: prepare
    runs-on: ubuntu-latest
      - run: echo $GITHUB_WORKSPACE/bin >> $GITHUB_PATH
      - run: fusesoc run --target=gpio_wb_tb caravel
      - run: fusesoc run --target=gpio_tb caravel
      - run: fusesoc run --target=pll_tb caravel

